import { ReactNode, useState } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/helixify.css";
import "@/styles/helixcolor.css";
import "@/styles/globals.scss";
import { Modal } from "@/components/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokedex",
  description: "Generated by PokeAPI",
};

const RootLayout = ({
  children,
  modal,
}: {
  children: ReactNode;
  modal: ReactNode;
}) => {
  return (
    // <Modal.ContextProvider>
    <html lang="en">
      <body className={inter.className}>
        {children}
        {modal}
      </body>
    </html>
    // </Modal.ContextProvider>
  );
};

export default RootLayout;
